using System.Text.Json;using SmartOrganizer.WinUI.Models;
namespace SmartOrganizer.WinUI.Services;
public sealed class FirstSeenStore
{
 readonly SemaphoreSlim gate=new(1,1);readonly FileIdentityService identities=new();readonly string path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SmartOrganizer","identity-ledger-v2.json");readonly string legacyPath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SmartOrganizer","first-seen.json");Dictionary<string,IdentityLedgerEntry>? entries;
 public async Task<IReadOnlyDictionary<string,FirstSeenResolution>> ResolveAsync(IEnumerable<string> paths,CancellationToken token)
 {
  await gate.WaitAsync(token);try{entries??=await LoadAsync(token);var result=new Dictionary<string,FirstSeenResolution>(StringComparer.OrdinalIgnoreCase);var changed=false;foreach(var p in paths){token.ThrowIfCancellationRequested();IdentityObservation o;try{o=await identities.ObserveAsync(p,true,token);}catch{continue;}var key=o.Identity.StableKey;IdentityLedgerEntry? found=null;if(entries.TryGetValue(key,out var exact))found=exact;else if(o.ContentHash is not null)found=entries.Values.FirstOrDefault(x=>x.ContentHash==o.ContentHash&&x.Length==o.Length&&x.StableKey!=key);var now=DateTime.UtcNow;if(found is null){var first=LegacyFirstSeen(p)??now;found=new(key,first,p,null,o.Identity.VolumeId,o.Identity.FileId,o.Identity.FileSystem,o.Length,o.LastWriteUtc,o.ContentHash,now);entries[key]=found;changed=true;result[p]=new(first,key,o.Identity.Kind,null,false,false);continue;}var previous=found.CurrentPath;var cross=found.StableKey!=key&&o.ContentHash is not null;var moved=!previous.Equals(p,StringComparison.OrdinalIgnoreCase);if(cross){entries.Remove(found.StableKey);found=found with{StableKey=key,PreviousPath=previous,CurrentPath=p,VolumeId=o.Identity.VolumeId,FileId=o.Identity.FileId,FileSystem=o.Identity.FileSystem,Length=o.Length,LastWriteUtc=o.LastWriteUtc,ContentHash=o.ContentHash,LastObservedAt=now};entries[key]=found;changed=true;}else if(moved||found.LastWriteUtc!=o.LastWriteUtc){found=found with{PreviousPath=moved?previous:found.PreviousPath,CurrentPath=p,Length=o.Length,LastWriteUtc=o.LastWriteUtc,ContentHash=o.ContentHash??found.ContentHash,LastObservedAt=now};entries[key]=found;changed=true;}result[p]=new(found.FirstSeenAt,key,cross?FileIdentityKind.ContentHashLink:o.Identity.Kind,moved?previous:null,moved,cross);}
   if(changed)await SaveAsync(token);return result;
  }finally{gate.Release();}
 }
 DateTime? LegacyFirstSeen(string p){try{if(!File.Exists(legacyPath))return null;var old=JsonSerializer.Deserialize<Dictionary<string,DateTime>>(File.ReadAllText(legacyPath));return old is not null&&old.TryGetValue(p,out var at)?at:null;}catch{return null;}}
 async Task<Dictionary<string,IdentityLedgerEntry>> LoadAsync(CancellationToken token){if(!File.Exists(path))return new(StringComparer.OrdinalIgnoreCase);try{await using var s=File.OpenRead(path);return await JsonSerializer.DeserializeAsync<Dictionary<string,IdentityLedgerEntry>>(s,cancellationToken:token)??new(StringComparer.OrdinalIgnoreCase);}catch{return new(StringComparer.OrdinalIgnoreCase);}}
 async Task SaveAsync(CancellationToken token){Directory.CreateDirectory(Path.GetDirectoryName(path)!);var temp=path+".tmp";await using(var s=new FileStream(temp,FileMode.Create,FileAccess.Write,FileShare.None,65536,true)){await JsonSerializer.SerializeAsync(s,entries,cancellationToken:token);await s.FlushAsync(token);}File.Move(temp,path,true);}
}
