using System.Collections.ObjectModel;using System.ComponentModel;using System.Runtime.CompilerServices;using Microsoft.UI.Dispatching;using SmartOrganizer.WinUI.Models;using SmartOrganizer.WinUI.Services;
namespace SmartOrganizer.WinUI.ViewModels;
public sealed class MainViewModel:INotifyPropertyChanged,IDisposable
{
 readonly IReadOnlyFileCatalog catalog;readonly FileCatalogWatcher watcher;readonly ChangeTrackingCoordinator changeTracking=new();readonly DispatcherQueue dispatcher;readonly FolderSettingsService folders;readonly FutureFolderAccessService futureAccess=new();readonly LazyOriginLoader originLoader=new();readonly List<FileRow> allResults=[];const int PageSize=200;int loadedCount;CancellationTokenSource? originCts;CancellationTokenSource? queryCts;long generation;bool disposed;string currentFolder,category="ALL",search="",smartView="ALL";string? kind,source,extension,relativeFolder;SortMode sort=SortMode.Newest;string status="準備完了";int visibleCount,totalCount;
 public ObservableCollection<DuplicateGroupRow> DuplicateGroups{get;}=[];public ObservableCollection<CategoryRow> Categories{get;}=[];public ObservableCollection<FileRow> Files{get;}=[];public ObservableCollection<string> Kinds{get;}=[];public ObservableCollection<string> Sources{get;}=[];public ObservableCollection<string> Extensions{get;}=[];public ObservableCollection<string> Subfolders{get;}=[];public ObservableCollection<QuickAccessRow> QuickAccess{get;}=[];
 public string CurrentFolder{get=>currentFolder;private set=>Set(ref currentFolder,value);}public bool IncludeSubfolders{get=>folders.IncludeSubfolders;set{if(folders.IncludeSubfolders==value)return;folders.IncludeSubfolders=value;OnPropertyChanged();watcher.Start(CurrentFolder,IncludeSubfolders);_=RefreshAsync(true);}}
 public string Category{get=>category;set{if(Set(ref category,value))_=RefreshAsync();}}public string Search{get=>search;set{if(Set(ref search,value))_=RefreshAsync();}}public string? Kind{get=>kind;set{if(Set(ref kind,value))_=RefreshAsync();}}public string? Source{get=>source;set{if(Set(ref source,value))_=RefreshAsync();}}public string? Extension{get=>extension;set{if(Set(ref extension,value))_=RefreshAsync();}}public string? RelativeFolder{get=>relativeFolder;set{if(Set(ref relativeFolder,value))_=RefreshAsync();}}public SortMode Sort{get=>sort;set{if(Set(ref sort,value))_=RefreshAsync();}}public string SmartView{get=>smartView;set{if(Set(ref smartView,value))_=RefreshAsync();}}
 public long LargeThresholdBytes{get=>folders.LargeThresholdBytes;set{folders.LargeThresholdBytes=value;OnPropertyChanged();_=RefreshAsync();}}public int RecentDays{get=>folders.RecentDays;set{folders.RecentDays=value;OnPropertyChanged();_=RefreshAsync();}}public bool HasMore=>loadedCount<allResults.Count;public string ActiveFiltersText=>$"{(SmartView!="ALL"?$"表示: {SmartView}  ":"")}{(!string.IsNullOrWhiteSpace(Search)?$"検索: {Search}  ":"")}{(Kind is not null?$"種類: {Kind}  ":"")}{(Source is not null?$"入手元: {Source}  ":"")}{(Extension is not null?$"拡張子: {Extension}  ":"")}{(RelativeFolder is not null?$"フォルダー: {RelativeFolder}":"")}".Trim();public void ClearFilters(){category="ALL";search="";kind=null;source=null;extension=null;relativeFolder=null;smartView="ALL";OnPropertyChanged(nameof(Category));OnPropertyChanged(nameof(Search));OnPropertyChanged(nameof(Kind));OnPropertyChanged(nameof(Source));OnPropertyChanged(nameof(Extension));OnPropertyChanged(nameof(RelativeFolder));OnPropertyChanged(nameof(SmartView));OnPropertyChanged(nameof(ActiveFiltersText));_=RefreshAsync();}public string Status{get=>status;private set=>Set(ref status,value);}public int VisibleCount{get=>visibleCount;private set=>Set(ref visibleCount,value);}public int TotalCount{get=>totalCount;private set=>Set(ref totalCount,value);}
 public MainViewModel():this(new ReadOnlyFileCatalog(),new FileCatalogWatcher(),DispatcherQueue.GetForCurrentThread(),new FolderSettingsService(new SettingsService())){}
 public MainViewModel(IReadOnlyFileCatalog catalog,FileCatalogWatcher watcher,DispatcherQueue dispatcher,FolderSettingsService folders){this.catalog=catalog;this.watcher=watcher;this.dispatcher=dispatcher;this.folders=folders;currentFolder=folders.GetRoot();BuildQuickAccess();watcher.Signaled+=OnWatcherSignal;watcher.Start(CurrentFolder,IncludeSubfolders);}
 public void ChangeFolder(string path){folders.SetRoot(path);CurrentFolder=folders.GetRoot();RelativeFolder=null;BuildQuickAccess();watcher.Start(CurrentFolder,IncludeSubfolders);_=RefreshAsync(true);}public void SelectQuickAccess(QuickAccessRow item){if(item.Path is not null)ChangeFolder(item.Path);SmartView=item.ViewMode;}
 void BuildQuickAccess(){QuickAccess.Clear();Add("CURRENT","現在の場所","\uE8B7",CurrentFolder,"ALL");Add("DOWNLOADS","ダウンロード","\uE896",Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)+"\\Downloads","ALL");Add("DESKTOP","デスクトップ","\uE8FC",Environment.GetFolderPath(Environment.SpecialFolder.Desktop),"ALL");Add("DOCUMENTS","ドキュメント","\uE8A5",Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"ALL");Add("RECENT","最近追加","\uE823",null,"RECENT");Add("LARGE","大きいファイル","\uE8B7",null,"LARGE");Add("DUPLICATES","重複候補","\uE8C8",null,"DUPLICATES");Add("CLEANUP","片付け候補","\uE74D",null,"CLEANUP");}void Add(string id,string label,string glyph,string? path,string mode){if(path is null||Directory.Exists(path))QuickAccess.Add(new(id,label,glyph,path,mode));}
 void OnWatcherSignal(object? sender,WatcherSignal signal){dispatcher.TryEnqueue(async()=>{if(disposed)return;if(signal==WatcherSignal.Changed){Status="変更を反映中";await RefreshAsync();return;}Status=signal==WatcherSignal.OverflowOrError?"監視通知を再同期中":"差分を確認中";using var c=new CancellationTokenSource(TimeSpan.FromSeconds(30));var delta=await changeTracking.CheckAsync(CurrentFolder,c.Token);if(delta.Disposition==DeltaRefreshDisposition.NoChanges){Status="監視中";return;}await RefreshAsync(delta.Disposition==DeltaRefreshDisposition.FullRescan);if(signal==WatcherSignal.OverflowOrError)watcher.Start(CurrentFolder,IncludeSubfolders);Status=delta.Reason;});}
 public async Task RefreshAsync(bool forceFullRescan=false){var myGeneration=Interlocked.Increment(ref generation);queryCts?.Cancel();queryCts?.Dispose();var c=queryCts=new();Status=SmartView=="DUPLICATES"?"重複候補を検査中":SmartView=="CLEANUP"?"片付け候補を分析中":forceFullRescan?"全件再同期中":"読み込み中";try{var r=await catalog.QueryAsync(CurrentFolder,new(Category,Search,Kind,Source,Extension,Sort,IncludeSubfolders,RelativeFolder,SmartView,folders.LargeThresholdBytes,folders.RecentDays,SmartView=="DUPLICATES",new Progress<CatalogProgress>(p=>dispatcher.TryEnqueue(()=>Status=p.Message))),c.Token);if(myGeneration!=Volatile.Read(ref generation)||disposed)return;await RunOnUiAsync(()=>{if(myGeneration!=Volatile.Read(ref generation)||disposed)return;allResults.Clear();allResults.AddRange(r.Files);loadedCount=0;Files.Clear();LoadNextPage();Replace(DuplicateGroups,r.Files.Where(x=>x.DuplicateGroup is not null).GroupBy(x=>x.DuplicateGroup!).Select(g=>new DuplicateGroupRow(g.Key,g.First().Length,g.ToArray())));Replace(Categories,r.Categories);Replace(Kinds,r.Filters.Kinds);Replace(Sources,r.Filters.Sources);Replace(Extensions,r.Filters.Extensions);Replace(Subfolders,r.Filters.Subfolders);VisibleCount=r.Files.Count;TotalCount=r.TotalCount;Status="監視中";});}catch(OperationCanceledException){}catch(Exception e){if(myGeneration==Volatile.Read(ref generation))await RunOnUiAsync(()=>Status=$"読み込み失敗: {e.Message}");}}
 public void LoadNextPage(){if(disposed)return;var page=allResults.Skip(loadedCount).Take(PageSize).ToArray();foreach(var row in page)Files.Add(row);loadedCount+=page.Length;OnPropertyChanged(nameof(HasMore));_ = LoadOriginsAsync(page);}
 async Task LoadOriginsAsync(IEnumerable<FileRow> page){originCts?.Cancel();originCts?.Dispose();var c=originCts=new();foreach(var row in page){try{var loaded=await originLoader.LoadAsync(row,c.Token);if(c.IsCancellationRequested||disposed)return;await RunOnUiAsync(()=>{var index=Files.IndexOf(row);if(index>=0)Files[index]=loaded with{OriginLoaded=true};});}catch(OperationCanceledException){return;}catch(IOException){}}}
 Task RunOnUiAsync(Action action){if(dispatcher.HasThreadAccess){action();return Task.CompletedTask;}var tcs=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);if(!dispatcher.TryEnqueue(()=>{try{action();tcs.SetResult();}catch(Exception e){tcs.SetException(e);}}))tcs.SetException(new InvalidOperationException("UIスレッドへ処理を戻せませんでした"));return tcs.Task;}static void Replace<T>(ObservableCollection<T> target,IEnumerable<T> source){target.Clear();foreach(var x in source)target.Add(x);}bool Set<T>(ref T field,T value,[CallerMemberName]string? name=null){if(EqualityComparer<T>.Default.Equals(field,value))return false;field=value;PropertyChanged?.Invoke(this,new(name));PropertyChanged?.Invoke(this,new(nameof(ActiveFiltersText)));return true;}void OnPropertyChanged([CallerMemberName]string? name=null)=>PropertyChanged?.Invoke(this,new(name));public event PropertyChangedEventHandler? PropertyChanged;public void Dispose(){disposed=true;Interlocked.Increment(ref generation);queryCts?.Cancel();queryCts?.Dispose();originCts?.Cancel();originCts?.Dispose();watcher.Signaled-=OnWatcherSignal;watcher.Dispose();}
}
