using System.Diagnostics;using Microsoft.UI.Input;using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using Microsoft.UI.Xaml.Controls.Primitives;using Microsoft.UI.Xaml.Input;using SmartOrganizer.WinUI.Models;using SmartOrganizer.WinUI.Operations;using SmartOrganizer.WinUI.Services;using SmartOrganizer.WinUI.ViewModels;
namespace SmartOrganizer.WinUI;
public sealed partial class MainWindow:Window
{
 public MainViewModel ViewModel{get;}=new();readonly SettingsService settings=new();readonly AdvancedOperationSettings advancedSettings;readonly ProtectedOperationService protectedOperations;readonly AppearanceService appearance;readonly ColumnLayoutService columns;readonly WindowPlacementService placement;
 readonly IOperationService operations;readonly BatchOperationService batches;readonly UndoCandidateService undoCandidates;CancellationTokenSource? operationCts;Guid? lastCompletedOperation;readonly DispatcherTimer searchTimer=new(){Interval=TimeSpan.FromMilliseconds(300)};public MainWindow(){advancedSettings=new(settings);protectedOperations=new(new SafeOperationService(),advancedSettings);operations=protectedOperations;batches=new(operations);undoCandidates=new(operations);appearance=new(settings);columns=new(settings);placement=new(settings);InitializeComponent();searchTimer.Tick+=(_,_)=>{searchTimer.Stop();ViewModel.Search=SearchBox.Text;};ApplyColumns();appearance.Apply(Root,appearance.Theme);ApplyDensity();placement.Restore(AppWindow);AppWindow.Closing+=(_,_)=>{columns.Save();placement.Save(AppWindow);operationCts?.Cancel();ViewModel.Dispose();};_ = InitializeAsync();_ = InspectRecoveryOnStartupAsync();}
 void ApplyColumns(){var w=columns.Widths;NameColumn.Width=new(w.Name);KindColumn.Width=new(w.Kind);SourceColumn.Width=new(w.Source);ModifiedColumn.Width=new(w.Modified);SizeColumn.Width=new(w.Size);TableExtent.Width=Math.Max(1050,w.Extent);TableExtent.MinWidth=TableExtent.Width;}
 void ColumnSplitter_DragDelta(object sender,DragDeltaEventArgs e){if(sender is Thumb t&&int.TryParse(t.Tag?.ToString(),out var i)){columns.Set(i,(i switch{0=>NameColumn.Width.Value,1=>KindColumn.Width.Value,2=>SourceColumn.Width.Value,3=>ModifiedColumn.Width.Value,_=>SizeColumn.Width.Value})+e.HorizontalChange);ApplyColumns();}}
 void ApplyDensity(){var compact=appearance.Density==UiDensity.Compact;CategoryList.MaxHeight=double.PositiveInfinity;FileList.Padding=new Thickness(0);Root.Resources["ListViewItemMinHeight"]=compact?30d:36d;}
 void Refresh_Click(object s,RoutedEventArgs e)=>Refresh();void Refresh_Invoked(KeyboardAccelerator s,KeyboardAcceleratorInvokedEventArgs e){Refresh();e.Handled=true;}void Refresh()=>_ = ViewModel.RefreshAsync();
 void Search_Invoked(KeyboardAccelerator s,KeyboardAcceleratorInvokedEventArgs e){SearchBox.Focus(FocusState.Keyboard);e.Handled=true;}async void Location_Invoked(KeyboardAccelerator s,KeyboardAcceleratorInvokedEventArgs e){e.Handled=true;await ChangeFolderAsync();}
 void SystemTheme_Click(object s,RoutedEventArgs e)=>appearance.Apply(Root,AppTheme.System);void LightTheme_Click(object s,RoutedEventArgs e)=>appearance.Apply(Root,AppTheme.Light);void DarkTheme_Click(object s,RoutedEventArgs e)=>appearance.Apply(Root,AppTheme.Dark);
 void StandardDensity_Click(object s,RoutedEventArgs e){appearance.SetDensity(UiDensity.Standard);ApplyDensity();}void CompactDensity_Click(object s,RoutedEventArgs e){appearance.SetDensity(UiDensity.Compact);ApplyDensity();}
 void SearchBox_TextChanged(AutoSuggestBox s,AutoSuggestBoxTextChangedEventArgs e){searchTimer.Stop();searchTimer.Start();}
 void CategoryList_ItemClick(object s,ItemClickEventArgs e){if(e.ClickedItem is CategoryRow c)ViewModel.Category=c.Id;}
 void QuickAccessList_ItemClick(object s,ItemClickEventArgs e){if(e.ClickedItem is QuickAccessRow q)ViewModel.SelectQuickAccess(q);}
 void SubfolderFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ViewModel.RelativeFolder=SubfolderFilter.SelectedItem as string;
 async void ChangeFolder_Click(object s,RoutedEventArgs e)=>await ChangeFolderAsync();
 void IncludeSubfolders_Click(object s,RoutedEventArgs e){if(s is ToggleMenuFlyoutItem item)ViewModel.IncludeSubfolders=item.IsChecked;}
 async Task InitializeAsync(){await ViewModel.RestoreFutureFolderAsync();await ViewModel.RefreshAsync();}
 async Task ChangeFolderAsync(){var picker=new Windows.Storage.Pickers.FolderPicker();var hwnd=WinRT.Interop.WindowNative.GetWindowHandle(this);WinRT.Interop.InitializeWithWindow.Initialize(picker,hwnd);picker.FileTypeFilter.Add("*");var folder=await picker.PickSingleFolderAsync();if(folder is not null)ViewModel.RememberFutureFolder(folder);}

 void LoadMore_Click(object s,RoutedEventArgs e)=>ViewModel.LoadNextPage();
 async void RecentDays_Click(object s,RoutedEventArgs e){var box=new NumberBox{Minimum=1,Maximum=365,Value=ViewModel.RecentDays,SpinButtonPlacementMode=NumberBoxSpinButtonPlacementMode.Compact};var d=new ContentDialog{Title="最近追加とする日数",Content=box,PrimaryButtonText="保存",CloseButtonText="キャンセル",XamlRoot=Root.XamlRoot};if(await d.ShowAsync()==ContentDialogResult.Primary)ViewModel.RecentDays=(int)box.Value;}
 async void LargeThreshold_Click(object s,RoutedEventArgs e){var box=new NumberBox{Minimum=1,Maximum=102400,Value=ViewModel.LargeThresholdBytes/1024d/1024d,SpinButtonPlacementMode=NumberBoxSpinButtonPlacementMode.Compact,Header="MB"};var d=new ContentDialog{Title="大きいファイルのしきい値",Content=box,PrimaryButtonText="保存",CloseButtonText="キャンセル",XamlRoot=Root.XamlRoot};if(await d.ShowAsync()==ContentDialogResult.Primary)ViewModel.LargeThresholdBytes=(long)(box.Value*1024*1024);}
 void ClearFilters_Click(object s,RoutedEventArgs e){SearchBox.Text="";KindFilter.SelectedItem=null;SourceFilter.SelectedItem=null;ExtensionFilter.SelectedItem=null;SubfolderFilter.SelectedItem=null;ViewModel.ClearFilters();}
 void KindFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ViewModel.Kind=KindFilter.SelectedItem as string;
 void SourceFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ViewModel.Source=SourceFilter.SelectedItem as string;
 void ExtensionFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ViewModel.Extension=ExtensionFilter.SelectedItem as string;
 void SortFilter_SelectionChanged(object s,SelectionChangedEventArgs e)=>ViewModel.Sort=(SortMode)Math.Max(0,SortFilter.SelectedIndex);
 void FileList_DoubleTapped(object s,DoubleTappedRoutedEventArgs e){if(FileList.SelectedItem is FileRow f)Process.Start(new ProcessStartInfo(f.FullPath){UseShellExecute=true});}

 async Task<bool> AuthorizeProtectedSelectionsAsync(IEnumerable<FileRow> selected){foreach(var row in selected){var request=protectedOperations.GetRequest(row.FullPath);if(request is null)continue;if(request.BlockKind==StructureBlockKind.SystemArea){await ShowMessage("Windowsの重要領域は高度な設定でも変更できません");return false;}if(advancedSettings.Mode!=FileOperationMode.Advanced){await ShowMessage("この項目はアプリまたはプロジェクトの構成内です。設定で『高度なファイル操作』を有効にすると、確認後に操作できます");return false;}if(!protectedOperations.RequiresConfirmation(request))continue;var remember=new CheckBox{Content="この一式では今後確認しない",IsChecked=false};var panel=new StackPanel{Spacing=12};panel.Children.Add(new TextBlock{Text=$"{request.Message}\n\n対象: {request.SourcePath}\n一式: {request.BlockRoot}\n\n内容を理解したうえで、この操作だけを許可します。",TextWrapping=TextWrapping.Wrap});panel.Children.Add(remember);var d=new ContentDialog{Title="保護された構成への操作",Content=panel,PrimaryButtonText="許可して続行",CloseButtonText="キャンセル",DefaultButton=ContentDialogButton.Close,XamlRoot=Root.XamlRoot};if(await d.ShowAsync()!=ContentDialogResult.Primary)return false;protectedOperations.AuthorizeOnce(request);if(remember.IsChecked==true)protectedOperations.Trust(request);}return true;}
 async void Settings_Click(object s,RoutedEventArgs e){var mode=new RadioButtons{Header="ファイル操作",Items={"通常: アプリやプロジェクトの内部操作を止める","高度: 確認後に内部操作を許可する"},SelectedIndex=advancedSettings.Mode==FileOperationMode.Advanced?1:0};var confirmation=new ComboBox{Header="高度な操作の確認",Items={"毎回確認する","一式ごとに最初の1回だけ確認する","確認しない"},SelectedIndex=(int)advancedSettings.Confirmation};var reset=new CheckBox{Content="保存済みの確認省略をすべて解除する"};var panel=new StackPanel{Spacing=16};panel.Children.Add(mode);panel.Children.Add(confirmation);panel.Children.Add(reset);var d=new ContentDialog{Title="設定",Content=panel,PrimaryButtonText="保存",CloseButtonText="キャンセル",DefaultButton=ContentDialogButton.Primary,XamlRoot=Root.XamlRoot};if(await d.ShowAsync()!=ContentDialogResult.Primary)return;advancedSettings.Mode=mode.SelectedIndex==1?FileOperationMode.Advanced:FileOperationMode.Standard;advancedSettings.Confirmation=(ProtectedOperationConfirmation)Math.Max(0,confirmation.SelectedIndex);if(reset.IsChecked==true)advancedSettings.ResetTrusted();await ViewModel.RefreshAsync(true);}
 async Task PreviewAndExecuteAsync(OperationKind kind)
 {
  var selected=FileList.SelectedItems.Cast<FileRow>().Where(x=>x.PresentationKind==EntryPresentationKind.SingleFile).ToArray();if(selected.Length==0){await ShowMessage("操作するファイルを1つ以上選択してください");return;}if(!await AuthorizeProtectedSelectionsAsync(selected))return;
  var picker=new Windows.Storage.Pickers.FolderPicker();var hwnd=WinRT.Interop.WindowNative.GetWindowHandle(this);WinRT.Interop.InitializeWithWindow.Initialize(picker,hwnd);picker.FileTypeFilter.Add("*");var folder=await picker.PickSingleFolderAsync();if(folder is null)return;
  var policy=await AskConflictPolicyAsync();if(policy is null)return;var plan=await batches.PreviewAsync(kind,selected.Select(x=>x.FullPath),folder.Path,policy.Value,CancellationToken.None);
  var ready=plan.Items.Count(x=>x.State==BatchItemState.Ready);var skipped=plan.Items.Count-ready;var preview=string.Join("\n",plan.Items.Take(50).Select(x=>$"{Path.GetFileName(x.SourcePath)} → {Path.GetFileName(x.DestinationPath)}{(x.State==BatchItemState.Skipped?$"  [{x.Reason}]":"")}"));
  var confirm=new ContentDialog{Title=kind==OperationKind.Copy?"コピー内容を確認":"移動内容を確認",Content=new ScrollViewer{MaxHeight=460,Content=new TextBlock{Text=$"実行: {ready}件 / スキップ: {skipped}件\n\n{preview}",TextWrapping=TextWrapping.Wrap}},PrimaryButtonText=kind==OperationKind.Copy?"コピー":"移動",CloseButtonText="キャンセル",DefaultButton=ContentDialogButton.Close,XamlRoot=Root.XamlRoot};if(ready==0||await confirm.ShowAsync()!=ContentDialogResult.Primary)return;
  operationCts?.Cancel();operationCts=new();CancelOperationButton.Visibility=Visibility.Visible;CancelOperationButton.IsEnabled=true;var progress=new Progress<OperationProgress>(p=>{OperationStatus.Text=$"{p.Stage} {p.Message}";CancelOperationButton.IsEnabled=p.CancellationBoundary==CancellationBoundary.Allowed;CancelOperationButton.Content=p.CancellationBoundary==CancellationBoundary.Allowed?"キャンセル":"確定中";});var result=await batches.ExecuteAsync(plan,progress,operationCts.Token);CancelOperationButton.IsEnabled=false;CancelOperationButton.Visibility=Visibility.Collapsed;lastCompletedOperation=result.Items.LastOrDefault(x=>x.State==BatchItemState.Completed)?.OperationId;await ShowBatchResults(result);await ViewModel.RefreshAsync();
 }
 async Task<NameConflictPolicy?> AskConflictPolicyAsync(){var d=new ContentDialog{Title="同名ファイルがある場合",Content="既存ファイルは上書きしません。処理方法を選んでください。",PrimaryButtonText="スキップ",SecondaryButtonText="名前を変更して保存",CloseButtonText="中止",DefaultButton=ContentDialogButton.Close,XamlRoot=Root.XamlRoot};return await d.ShowAsync() switch{ContentDialogResult.Primary=>NameConflictPolicy.Skip,ContentDialogResult.Secondary=>NameConflictPolicy.Rename,_=>null};}
 async Task ShowBatchResults(BatchOperationResult r){var lines=r.Items.Select(x=>$"{x.State}: {Path.GetFileName(x.SourcePath)} → {Path.GetFileName(x.DestinationPath)}\n  {x.Message}");var d=new ContentDialog{Title=$"結果  成功{r.Completed} / スキップ{r.Skipped} / 失敗{r.Failed} / キャンセル{r.Cancelled}",Content=new ScrollViewer{MaxHeight=480,Content=new TextBlock{Text=string.Join("\n",lines),TextWrapping=TextWrapping.Wrap}},CloseButtonText="閉じる",XamlRoot=Root.XamlRoot};await d.ShowAsync();}
 async void PreviewCopy_Click(object s,RoutedEventArgs e)=>await PreviewAndExecuteAsync(OperationKind.Copy);
 async void PreviewMove_Click(object s,RoutedEventArgs e)=>await PreviewAndExecuteAsync(OperationKind.Move);
 async void Undo_Click(object s,RoutedEventArgs e){var record=lastCompletedOperation is Guid id?(await operations.HistoryAsync(CancellationToken.None)).FirstOrDefault(x=>x.Id==id):await undoCandidates.LatestAsync(CancellationToken.None);if(record is null){await ShowMessage("Undoできる完了操作がありません");return;}var d=new ContentDialog{Title="この操作をUndoしますか",Content=new TextBlock{Text=UndoCandidateService.Describe(record),TextWrapping=TextWrapping.Wrap},PrimaryButtonText="Undo",CloseButtonText="キャンセル",DefaultButton=ContentDialogButton.Close,XamlRoot=Root.XamlRoot};if(await d.ShowAsync()!=ContentDialogResult.Primary)return;var result=await operations.UndoAsync(record.Id,CancellationToken.None);await ShowMessage(result.Message);if(result.Success)lastCompletedOperation=null;await ViewModel.RefreshAsync();}
 void ContextOpen_Click(object s,RoutedEventArgs e){if(FileList.SelectedItem is FileRow f)Process.Start(new ProcessStartInfo(f.FullPath){UseShellExecute=true});}
 void ContextOpenFolder_Click(object s,RoutedEventArgs e){if(FileList.SelectedItem is FileRow f)Process.Start(new ProcessStartInfo("explorer.exe",$"/select,\"{f.FullPath}\""){UseShellExecute=true});}
 void ContextCopyPath_Click(object s,RoutedEventArgs e){if(FileList.SelectedItem is FileRow f){var package=new Windows.ApplicationModel.DataTransfer.DataPackage();package.SetText(f.FullPath);Windows.ApplicationModel.DataTransfer.Clipboard.SetContent(package);}}
 async void Details_Click(object s,RoutedEventArgs e){if(FileList.SelectedItem is not FileRow f)return;var info=new FileInfo(f.FullPath);var zone=ReadZoneSummary(f.FullPath);var cleanup=f.IsCleanupSuggestion?$"\n片付け候補: {CleanupLabel(f.CleanupKind)}\n確度: {f.CleanupConfidence}\n理由: {f.CleanupReason}\n状態: 提案のみ。自動削除しません":"";var text=$"名前: {f.Name}\nパス: {f.FullPath}\n種類: {f.Kind}\n拡張子: {f.Extension}\nサイズ: {f.Size} ({f.Length:N0} bytes)\n作成日時: {info.CreationTime:g}\n更新日時: {info.LastWriteTime:g}\n属性: {info.Attributes}\n取得元: {f.Source}\nZone情報: {zone}{cleanup}";var d=new ContentDialog{Title="ファイルの詳細",Content=new ScrollViewer{MaxHeight=480,Content=new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap}},CloseButtonText="閉じる",XamlRoot=Root.XamlRoot};await d.ShowAsync();}
 static string CleanupLabel(CleanupCandidateKind? kind)=>kind switch{CleanupCandidateKind.TemporaryFile=>"一時ファイル",CleanupCandidateKind.IncompleteDownload=>"未完了ダウンロード",CleanupCandidateKind.LogOrCache=>"ログ・キャッシュ",CleanupCandidateKind.OldVersion=>"旧バージョン",CleanupCandidateKind.OrphanFile=>"孤立ファイル",CleanupCandidateKind.Installer=>"インストーラー",_=>""};
 static string ReadZoneSummary(string path){try{var ads=path+":Zone.Identifier";return File.Exists(ads)?string.Join("; ",File.ReadAllLines(ads).Where(x=>x.StartsWith("ZoneId=")||x.StartsWith("HostUrl=")||x.StartsWith("ReferrerUrl="))):"なし";}catch{return "読み取り不可";}}
 void CancelOperation_Click(object s,RoutedEventArgs e){if(operationCts is {IsCancellationRequested:false} && CancelOperationButton.IsEnabled){CancelOperationButton.IsEnabled=false;CancelOperationButton.Content="停止を待っています";operationCts.Cancel();}}
 async Task InspectRecoveryOnStartupAsync(){var candidates=await operations.InspectRecoveryAsync(CancellationToken.None);if(candidates.Count==0)return;var text=string.Join("\n\n",candidates.Select(x=>$"{x.Record.Kind}: {x.Record.SourcePath}\n→ {x.Record.DestinationPath}\n{x.Recommendation}"));var d=new ContentDialog{Title="未完了の操作を検出しました",Content=new ScrollViewer{MaxHeight=420,Content=new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap}},CloseButtonText="確認しました",XamlRoot=Root.XamlRoot};await d.ShowAsync();}

 async Task ShowMessage(string message){var d=new ContentDialog{Title="SmartOrganizer",Content=new TextBlock{Text=message,TextWrapping=TextWrapping.Wrap},CloseButtonText="閉じる",XamlRoot=Root.XamlRoot};await d.ShowAsync();}

 async void History_Click(object s,RoutedEventArgs e){var rows=await operations.HistoryAsync(CancellationToken.None);var text=rows.Count==0?"履歴はありません":string.Join("\n",rows.Take(100).Select(x=>$"{x.CreatedAt:g}  {x.Kind}  {x.State}  {x.DestinationPath}"));var dialog=new ContentDialog{Title="操作履歴",Content=new ScrollViewer{Content=new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap},MaxHeight=480},CloseButtonText="閉じる",XamlRoot=Root.XamlRoot};await dialog.ShowAsync();}
 void ResetColumns_Click(object s,RoutedEventArgs e){columns.Reset();ApplyColumns();columns.Save();TableScroll.ChangeView(0,null,null);}
}
