using System.Security.Cryptography;using SmartOrganizer.WinUI.Operations;
static class Check{public static void True(bool ok,string name){if(!ok)throw new Exception("FAIL "+name);Console.WriteLine("PASS "+name);}public static async Task Throws<T>(Func<Task> f,string name)where T:Exception{try{await f();throw new Exception("FAIL "+name);}catch(T){Console.WriteLine("PASS "+name);}}}
var root=Path.Combine(Path.GetTempPath(),"SmartOrganizerTests",Guid.NewGuid().ToString("N"));var source=Path.Combine(root,"source");var dest=Path.Combine(root,"dest");Directory.CreateDirectory(source);Directory.CreateDirectory(dest);
try{
 var service=new SafeOperationService();var a=Path.Combine(source,"日本語.txt");await File.WriteAllTextAsync(a,"alpha");
 var cp=await service.PreviewAsync(OperationKind.Copy,a,dest,CancellationToken.None);Check.True(cp.BlockingReason is null,"copy preview");var cr=await service.ExecuteAsync(cp,null,CancellationToken.None);Check.True(cr.Success&&File.Exists(cp.DestinationPath)&&File.Exists(a),"copy execute");Check.True(SHA256.HashData(File.ReadAllBytes(a)).SequenceEqual(SHA256.HashData(File.ReadAllBytes(cp.DestinationPath))),"copy hash");var cu=await service.UndoAsync(cr.Record.Id,CancellationToken.None);Check.True(cu.Success&&!File.Exists(cp.DestinationPath)&&File.Exists(a),"copy undo");
 await File.WriteAllTextAsync(Path.Combine(dest,"日本語.txt"),"collision");var blocked=await service.PreviewAsync(OperationKind.Copy,a,dest,CancellationToken.None);Check.True(blocked.BlockingReason is not null,"overwrite blocked");File.Delete(Path.Combine(dest,"日本語.txt"));
 var mp=await service.PreviewAsync(OperationKind.Move,a,dest,CancellationToken.None);var mr=await service.ExecuteAsync(mp,null,CancellationToken.None);Check.True(mr.Success&&!File.Exists(a)&&File.Exists(mp.DestinationPath),"move execute");var mu=await service.UndoAsync(mr.Record.Id,CancellationToken.None);Check.True(mu.Success&&File.Exists(a)&&!File.Exists(mp.DestinationPath),"move undo");
 var large=Path.Combine(source,"cancel.bin");await File.WriteAllBytesAsync(large,new byte[16*1024*1024]);var plan=await service.PreviewAsync(OperationKind.Copy,large,dest,CancellationToken.None);using var cts=new CancellationTokenSource();cts.Cancel();var cancelled=await service.ExecuteAsync(plan,null,cts.Token);Check.True(!cancelled.Success&&!File.Exists(plan.DestinationPath),"cancel leaves no destination");Check.True(!Directory.EnumerateFiles(dest,"*.partial").Any(),"cancel removes partial");
 Console.WriteLine("ALL_OPERATION_TESTS_PASSED");
}finally{try{Directory.Delete(root,true);}catch{}}
