using SmartOrganizer.WinUI.Models;using SmartOrganizer.WinUI.Services;
namespace SmartOrganizer.WinUI.Operations;
public sealed class ProtectedOperationService:IOperationService
{
 readonly IOperationService inner;readonly StructureIndex index;readonly AdvancedOperationSettings settings;readonly HashSet<string> oneShot=new(StringComparer.OrdinalIgnoreCase);
 public ProtectedOperationService(IOperationService inner,AdvancedOperationSettings settings,StructureIndex? index=null){this.inner=inner;this.settings=settings;this.index=index??StructureIndex.Current;}
 public ProtectedOperationRequest? GetRequest(string sourcePath){var d=index.DecideOperation(sourcePath);if(d.Allowed)return null;if(d.State==ProtectionState.SystemProtected)return new(sourcePath,"",d.BlockRoot??"",StructureBlockKind.SystemArea,d.Message);return new(sourcePath,d.BlockId??"",d.BlockRoot??"",d.BlockKind??StructureBlockKind.UnknownBundle,d.Message);}
 public bool RequiresConfirmation(ProtectedOperationRequest r)=>!settings.IsTrusted(r.BlockId)&&(r.BlockKind==StructureBlockKind.UnknownBundle||settings.Confirmation==ProtectedOperationConfirmation.Always||settings.Confirmation==ProtectedOperationConfirmation.OncePerBlock);
 public void AuthorizeOnce(ProtectedOperationRequest r)=>oneShot.Add(r.SourcePath);public void Trust(ProtectedOperationRequest r)=>settings.Trust(r.BlockId);
 public async Task<OperationPlan> PreviewAsync(OperationKind kind,string sourcePath,string destinationFolder,CancellationToken token){var d=index.DecideOperation(sourcePath);if(d.Allowed)return await inner.PreviewAsync(kind,sourcePath,destinationFolder,token);var basePlan=await inner.PreviewAsync(kind,sourcePath,destinationFolder,token);if(d.State==ProtectionState.SystemProtected)return basePlan with{BlockingReason=d.Message};if(settings.Mode==FileOperationMode.Standard)return basePlan with{BlockingReason="通常設定ではアプリ・プロジェクト内部を操作しません。設定から高度なファイル操作を有効にできます"};var request=GetRequest(sourcePath)!;if(oneShot.Remove(sourcePath)||(!RequiresConfirmation(request)))return basePlan;return basePlan with{BlockingReason="PROTECTED_CONFIRMATION_REQUIRED"};}
 public Task<OperationResult> ExecuteAsync(OperationPlan plan,IProgress<OperationProgress>? progress,CancellationToken token){var d=index.DecideOperation(plan.SourcePath);if(d.State==ProtectionState.SystemProtected)throw new InvalidOperationException(d.Message);if(!d.Allowed&&settings.Mode!=FileOperationMode.Advanced)throw new InvalidOperationException("実行直前の保護確認で拒否しました");return inner.ExecuteAsync(plan,progress,token);}
 public Task<OperationResult> UndoAsync(Guid id,CancellationToken token)=>inner.UndoAsync(id,token);public Task<IReadOnlyList<OperationRecord>> HistoryAsync(CancellationToken token)=>inner.HistoryAsync(token);public Task<IReadOnlyList<OperationRecord>> RecoveryCandidatesAsync(CancellationToken token)=>inner.RecoveryCandidatesAsync(token);public Task<IReadOnlyList<RecoveryCandidate>> InspectRecoveryAsync(CancellationToken token)=>inner.InspectRecoveryAsync(token);
}
