using SmartOrganizer.WinUI.Models;
namespace SmartOrganizer.WinUI.Services;
public sealed class ReadOnlyFileCatalog:IReadOnlyFileCatalog
{
 static readonly HashSet<string> Docs=new(StringComparer.OrdinalIgnoreCase){".pdf",".doc",".docx",".txt",".rtf",".ppt",".pptx",".xls",".xlsx",".md"};static readonly HashSet<string> Images=new(StringComparer.OrdinalIgnoreCase){".png",".jpg",".jpeg",".gif",".webp",".bmp",".svg",".heic"};static readonly HashSet<string> Media=new(StringComparer.OrdinalIgnoreCase){".mp3",".wav",".m4a",".mp4",".mov",".mkv",".avi",".webm"};static readonly HashSet<string> Archives=new(StringComparer.OrdinalIgnoreCase){".zip",".7z",".rar",".tar",".gz"};static readonly HashSet<string> Data=new(StringComparer.OrdinalIgnoreCase){".csv",".json",".xml",".yaml",".yml",".db",".sqlite",".sql"};readonly DuplicateCandidateService duplicates=new();readonly SafeFileEnumerator enumerator=new();readonly FirstSeenStore firstSeen=new();readonly StructureAnalyzer structures=new();readonly AdvancedOperationSettings advanced=new(new SettingsService());readonly CleanupCandidateEngine cleanup=new();
 public Task<QueryResult> QueryAsync(string root,QueryOptions options,CancellationToken token)=>Task.Run(async()=>await Query(root,options,token),token);
 async Task<QueryResult> Query(string root,QueryOptions o,CancellationToken token)
 {
  var entries=new List<FileEntry>();var report=Directory.Exists(root)?enumerator.Enumerate(root,o.IncludeSubfolders,token):new EnumerationReport([],[],0);foreach(var path in report.Files){token.ThrowIfCancellationRequested();try{var f=new FileInfo(path);var rel=Path.GetRelativePath(root,f.DirectoryName??root);if(rel==".")rel="(直下)";entries.Add(new(f.FullName,f.Name,f.Extension.ToLowerInvariant(),f.Length,f.CreationTime,f.LastWriteTime,f.Attributes,rel));}catch(UnauthorizedAccessException){}catch(IOException){}}
  var analysis=structures.Analyze(root,entries,token);StructureIndex.Current.Replace(analysis.Blocks);var seen=await firstSeen.ResolveAsync(analysis.StandaloneFiles.Select(x=>x.FullPath),token);var rows=analysis.StandaloneFiles.Select(f=>new FileRow(f.Name,Kind(f.Extension),"読み込み待ち",f.ModifiedAt.ToString("yyyy/MM/dd HH:mm"),FormatSize(f.Length),f.Extension.TrimStart('.'),f.FullPath,f.Length,f.ModifiedAt,f.CreatedAt,f.RelativeFolder,null,seen.TryGetValue(f.FullPath,out var identity)?identity.FirstSeenAt:null,false,EntryPresentationKind.SingleFile,null,ProtectionState.None,DetectionConfidence.Confirmed,null,true)).Concat(analysis.Blocks.Select(b=>new FileRow(b.DisplayName,b.Kind==StructureBlockKind.PortableApplication?"アプリ一式":b.Kind==StructureBlockKind.DevelopmentProject?"開発プロジェクト":"要確認の一式","保護",b.ModifiedAt.ToString("yyyy/MM/dd HH:mm"),FormatSize(b.TotalLength),"",b.RootPath,b.TotalLength,b.ModifiedAt,b.ModifiedAt,Path.GetFileName(Path.GetDirectoryName(b.RootPath)??""),null,null,true,b.Kind==StructureBlockKind.UnknownBundle?EntryPresentationKind.UnknownBlock:EntryPresentationKind.StructureBlock,b.Id,b.Protection,b.Confidence,string.Join(" / ",b.Reasons.Select(x=>x.Description)),false))).ToArray();var cleanupCandidates=cleanup.Analyze(rows,analysis.Blocks,DateTime.UtcNow);rows=rows.Select(x=>cleanupCandidates.TryGetValue(x.FullPath,out var c)?x with{CleanupKind=c.Kind,CleanupConfidence=c.Confidence,CleanupReason=string.Join(" / ",c.Reasons.Select(r=>r.Description)),IsCleanupSuggestion=true}:x).ToArray();if(advanced.Mode==FileOperationMode.Advanced){var protectedMemberPaths=analysis.Blocks.SelectMany(b=>b.Members.Select(m=>(b,m)));var memberRows=protectedMemberPaths.Select(pair=>{var b=pair.b;var f=pair.m;return new FileRow("  "+f.Name,Kind(f.Extension),"構成内",f.ModifiedAt.ToString("yyyy/MM/dd HH:mm"),FormatSize(f.Length),f.Extension.TrimStart('.'),f.FullPath,f.Length,f.ModifiedAt,f.CreatedAt,f.RelativeFolder,null,null,true,EntryPresentationKind.SingleFile,b.Id,b.Protection,b.Confidence,string.Join(" / ",b.Reasons.Select(x=>x.Description)),false);});rows=rows.Concat(memberRows).ToArray();}var all=rows;if(o.FindDuplicates){var standalone=all.Where(x=>x.IsIndividuallyOperable&&x.PresentationKind==EntryPresentationKind.SingleFile).ToArray();var groups=await duplicates.FindAsync(standalone,o.Progress,token);all=standalone.Where(x=>groups.ContainsKey(x.FullPath)).Select(x=>x with{DuplicateGroup=groups[x.FullPath]}).ToArray();}
  IEnumerable<FileRow> q=all;if(o.Category!="ALL")q=q.Where(x=>CategoryOf(x.Kind)==o.Category);if(!string.IsNullOrWhiteSpace(o.Search))q=q.Where(x=>x.Name.Contains(o.Search,StringComparison.CurrentCultureIgnoreCase));if(!string.IsNullOrWhiteSpace(o.Kind))q=q.Where(x=>x.Kind==o.Kind);if(!string.IsNullOrWhiteSpace(o.Source))q=q.Where(x=>x.Source==o.Source);if(!string.IsNullOrWhiteSpace(o.Extension))q=q.Where(x=>x.Extension.Equals(o.Extension,StringComparison.OrdinalIgnoreCase));if(!string.IsNullOrWhiteSpace(o.RelativeFolder))q=q.Where(x=>x.RelativeFolder.Equals(o.RelativeFolder,StringComparison.OrdinalIgnoreCase));if(o.SmartView=="RECENT")q=q.Where(x=>x.IsIndividuallyOperable&&x.FirstSeenAt>=DateTime.UtcNow.AddDays(-o.RecentDays));if(o.SmartView=="LARGE")q=q.Where(x=>x.Length>=o.LargeFileThresholdBytes);if(o.SmartView=="CLEANUP")q=q.Where(x=>x.IsCleanupSuggestion);
  q=o.Sort switch{SortMode.Oldest=>q.OrderBy(x=>x.ModifiedAt),SortMode.NameAscending=>q.OrderBy(x=>x.Name,StringComparer.CurrentCultureIgnoreCase),SortMode.NameDescending=>q.OrderByDescending(x=>x.Name,StringComparer.CurrentCultureIgnoreCase),SortMode.SizeDescending=>q.OrderByDescending(x=>x.Length),SortMode.SizeAscending=>q.OrderBy(x=>x.Length),_=>q.OrderByDescending(x=>x.ModifiedAt)};
  var cats=new[]{Cat("ALL","すべて","\uE8B7",all.Length),Cat("DOC","文書","\uE8A5",all.Count(x=>CategoryOf(x.Kind)=="DOC")),Cat("PDF","PDF","\uEA90",all.Count(x=>x.Extension=="pdf")),Cat("IMAGE","画像","\uEB9F",all.Count(x=>CategoryOf(x.Kind)=="IMAGE")),Cat("MEDIA","音声・動画","\uE8B2",all.Count(x=>CategoryOf(x.Kind)=="MEDIA")),Cat("ARCHIVE","圧縮","\uF012",all.Count(x=>CategoryOf(x.Kind)=="ARCHIVE")),Cat("DATA","データ","\uE9F9",all.Count(x=>CategoryOf(x.Kind)=="DATA")),Cat("OTHER","その他","\uE10C",all.Count(x=>CategoryOf(x.Kind)=="OTHER"))};
  return new(q.ToArray(),cats,new(all.Select(x=>x.Kind).Distinct().Order().ToArray(),all.Select(x=>x.Source).Distinct().Order().ToArray(),all.Select(x=>x.Extension).Where(x=>x.Length>0).Distinct(StringComparer.OrdinalIgnoreCase).Order().ToArray(),all.Select(x=>x.RelativeFolder).Distinct(StringComparer.OrdinalIgnoreCase).Order().ToArray()),all.Length);
 }
 static CategoryRow Cat(string id,string label,string glyph,int count)=>new(id,label,glyph,count);static string Kind(string e)=>e.Equals(".pdf",StringComparison.OrdinalIgnoreCase)?"PDF":Docs.Contains(e)?"文書":Images.Contains(e)?"画像":Media.Contains(e)?"音声・動画":Archives.Contains(e)?"圧縮":Data.Contains(e)?"データ":"その他";static string CategoryOf(string kind)=>kind switch{"PDF"=>"PDF","文書"=>"DOC","画像"=>"IMAGE","音声・動画"=>"MEDIA","圧縮"=>"ARCHIVE","データ"=>"DATA",_=>"OTHER"};static string FormatSize(long n){string[] u={"B","KB","MB","GB","TB"};double v=n;var i=0;while(v>=1024&&i<u.Length-1){v/=1024;i++;}return $"{v:0.#} {u[i]}";}
}
