using System.Security.Cryptography;using System.Text;using SmartOrganizer.WinUI.Models;
namespace SmartOrganizer.WinUI.Services;
public sealed class StructureAnalyzer
{
 static readonly HashSet<string> AppDirs=new(StringComparer.OrdinalIgnoreCase){"runtime","resources","plugins","locales","lib","bin","assets"};static readonly HashSet<string> ProjectNames=new(StringComparer.OrdinalIgnoreCase){"package.json","pyproject.toml","requirements.txt","cargo.toml","go.mod","pom.xml","build.gradle"};
 public StructureAnalysis Analyze(string root,IEnumerable<FileEntry> source,CancellationToken token){var files=source.ToArray();var dirs=new[]{Path.GetFullPath(root)}.Concat(files.Select(x=>Path.GetDirectoryName(x.FullPath)!)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(Depth);var blocks=new List<StructureBlock>();foreach(var d in dirs){token.ThrowIfCancellationRequested();if(blocks.Any(b=>Child(d,b.RootPath)))continue;var m=files.Where(x=>Child(x.FullPath,d)).ToArray();var b=Detect(root,d,m);if(b is not null)blocks.Add(b);}var protectedPaths=blocks.SelectMany(x=>x.Members).Select(x=>x.FullPath).ToHashSet(StringComparer.OrdinalIgnoreCase);return new(files.Where(x=>!protectedPaths.Contains(x.FullPath)).ToArray(),blocks);}
 StructureBlock? Detect(string scanRoot,string dir,FileEntry[] m){string[] children;try{children=Directory.EnumerateDirectories(dir).Select(Path.GetFileName).Where(x=>x is not null).Cast<string>().ToArray();}catch{children=[];}var direct=m.Where(x=>Path.GetDirectoryName(x.FullPath)!.Equals(dir,StringComparison.OrdinalIgnoreCase)).ToArray();var reasons=new List<DetectionReason>();if(direct.Any(x=>x.Extension.Equals(".exe",StringComparison.OrdinalIgnoreCase))&&(direct.Any(x=>x.Extension.Equals(".dll",StringComparison.OrdinalIgnoreCase))||children.Any(AppDirs.Contains))){reasons.Add(new("APPLICATION_STRUCTURE","実行ファイルと構成部品を検出",80));return Make(dir,StructureBlockKind.PortableApplication,ProtectionState.BlockProtected,DetectionConfidence.High,reasons,m);}var project=direct.Any(x=>x.Extension is ".sln" or ".csproj" or ".vcxproj"||ProjectNames.Contains(x.Name));if(project&&children.Any(x=>x.Equals("src",StringComparison.OrdinalIgnoreCase)||x.Equals(".git",StringComparison.OrdinalIgnoreCase)||x.Equals("tests",StringComparison.OrdinalIgnoreCase))){reasons.Add(new("PROJECT_STRUCTURE","プロジェクト定義とソース構造を検出",80));return Make(dir,StructureBlockKind.DevelopmentProject,ProtectionState.BlockProtected,DetectionConfidence.High,reasons,m);}if(!Path.GetFullPath(dir).Equals(Path.GetFullPath(scanRoot),StringComparison.OrdinalIgnoreCase)&&m.Length>=3&&children.Length>0&&m.Count(x=>x.Extension is ".bin" or ".dat" or ".pak" or ".cfg" or ".ini")>=2){reasons.Add(new("UNKNOWN_RELATED_SET","用途を確定できない関連ファイル群",40));return Make(dir,StructureBlockKind.UnknownBundle,ProtectionState.ReviewRequired,DetectionConfidence.Low,reasons,m);}return null;}
 static StructureBlock Make(string root,StructureBlockKind kind,ProtectionState p,DetectionConfidence c,IReadOnlyList<DetectionReason> r,IReadOnlyList<FileEntry> m)=>new(Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(Path.GetFullPath(root).ToUpperInvariant()))),Path.GetFullPath(root),Path.GetFileName(root),kind,p,c,r,m,m.Sum(x=>x.Length),m.Max(x=>x.ModifiedAt));static int Depth(string p)=>p.Count(c=>c==Path.DirectorySeparatorChar);static bool Child(string p,string r){r=Path.GetFullPath(r).TrimEnd(Path.DirectorySeparatorChar);p=Path.GetFullPath(p);return p.Equals(r,StringComparison.OrdinalIgnoreCase)||p.StartsWith(r+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);}
}
