using System.ComponentModel;using System.Runtime.InteropServices;using Microsoft.Win32.SafeHandles;using SmartOrganizer.WinUI.Models;
namespace SmartOrganizer.WinUI.Services;
public sealed class UsnJournalReader
{
 const uint FSCTL_QUERY_USN_JOURNAL=0x000900f4,FSCTL_READ_USN_JOURNAL=0x000900bb;const uint GENERIC_READ=0x80000000,FILE_SHARE_READ=1,FILE_SHARE_WRITE=2,FILE_SHARE_DELETE=4,OPEN_EXISTING=3;
 [StructLayout(LayoutKind.Sequential)]struct USN_JOURNAL_DATA{public ulong JournalId;public long FirstUsn;public long NextUsn;public long LowestValidUsn;public long MaxUsn;public ulong MaximumSize;public ulong AllocationDelta;}
 [StructLayout(LayoutKind.Sequential)]struct READ_USN_JOURNAL_DATA{public long StartUsn;public uint ReasonMask;public uint ReturnOnlyOnClose;public ulong Timeout;public ulong BytesToWaitFor;public ulong JournalId;}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern SafeFileHandle CreateFile(string name,uint access,uint share,IntPtr security,uint creation,uint flags,IntPtr template);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool DeviceIoControl(SafeFileHandle h,uint code,IntPtr input,uint inputSize,IntPtr output,uint outputSize,out uint returned,IntPtr overlapped);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool GetVolumeInformation(string root,string? name,uint nameSize,out uint serial,out uint max,out uint flags,System.Text.StringBuilder fs,uint fsSize);
 public UsnJournalSnapshot Probe(string path)
 {
  var root=Path.GetPathRoot(Path.GetFullPath(path))??"";if(!OperatingSystem.IsWindows())return new(root,0,0,0,0,"Unknown",false,"Windows以外ではUSNを利用できません");var fs=new System.Text.StringBuilder(32);if(!GetVolumeInformation(root,null,0,out _,out _,out _,fs,(uint)fs.Capacity))return new(root,0,0,0,0,"Unknown",false,new Win32Exception(Marshal.GetLastWin32Error()).Message);if(!fs.ToString().Equals("NTFS",StringComparison.OrdinalIgnoreCase))return new(root,0,0,0,0,fs.ToString(),false,"NTFSではありません");try{using var h=Open(root);var data=Query(h);return new(root,data.JournalId,data.FirstUsn,data.NextUsn,data.LowestValidUsn,fs.ToString(),true,null);}catch(Exception e){return new(root,0,0,0,0,fs.ToString(),false,e.Message);}
 }
 public IReadOnlyList<UsnChange> Read(string root,ulong journalId,long startUsn,out long nextUsn)
 {
  using var h=Open(root);var input=new READ_USN_JOURNAL_DATA{StartUsn=startUsn,ReasonMask=0xffffffff,ReturnOnlyOnClose=0,Timeout=0,BytesToWaitFor=0,JournalId=journalId};var inputSize=Marshal.SizeOf<READ_USN_JOURNAL_DATA>();var inPtr=Marshal.AllocHGlobal(inputSize);var outSize=1024*1024;var outPtr=Marshal.AllocHGlobal(outSize);try{Marshal.StructureToPtr(input,inPtr,false);if(!DeviceIoControl(h,FSCTL_READ_USN_JOURNAL,inPtr,(uint)inputSize,outPtr,(uint)outSize,out var returned,IntPtr.Zero))throw new Win32Exception(Marshal.GetLastWin32Error());nextUsn=Marshal.ReadInt64(outPtr);var changes=new List<UsnChange>();var offset=8;while(offset+60<=returned){var p=IntPtr.Add(outPtr,offset);var length=Marshal.ReadInt32(p);if(length<=0||offset+length>returned)break;var major=(ushort)Marshal.ReadInt16(p,4);if(major==2){var frn=(ulong)Marshal.ReadInt64(p,8);var parent=(ulong)Marshal.ReadInt64(p,16);var usn=Marshal.ReadInt64(p,24);var reason=(uint)Marshal.ReadInt32(p,40);var nameLen=(ushort)Marshal.ReadInt16(p,56);var nameOff=(ushort)Marshal.ReadInt16(p,58);var name=Marshal.PtrToStringUni(IntPtr.Add(p,nameOff),nameLen/2)??"";changes.Add(new(frn,parent,usn,reason,name));}offset+=length;}return changes;}finally{Marshal.FreeHGlobal(inPtr);Marshal.FreeHGlobal(outPtr);}
 }
 SafeFileHandle Open(string root){var drive=root.TrimEnd('\\');var h=CreateFile("\\\\.\\"+drive,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,IntPtr.Zero,OPEN_EXISTING,0,IntPtr.Zero);if(h.IsInvalid)throw new Win32Exception(Marshal.GetLastWin32Error());return h;}USN_JOURNAL_DATA Query(SafeFileHandle h){var size=Marshal.SizeOf<USN_JOURNAL_DATA>();var p=Marshal.AllocHGlobal(size);try{if(!DeviceIoControl(h,FSCTL_QUERY_USN_JOURNAL,IntPtr.Zero,0,p,(uint)size,out _,IntPtr.Zero))throw new Win32Exception(Marshal.GetLastWin32Error());return Marshal.PtrToStructure<USN_JOURNAL_DATA>(p);}finally{Marshal.FreeHGlobal(p);}}
}
